apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    # K8s standard
    app.kubernetes.io/name: {{ include "web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http